name: Bash

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'Bash/*.sh'
      - 'Bash/.bashrc'
      - 'Bash/.bash_aliases'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'Bash/*.sh'
      - 'Bash/.bashrc'
      - 'Bash/.bash_aliases'
  workflow_dispatch:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC2059 -e SC1090
