name: PowerShell

on:
  push:
    branches: [ "main" ]
    paths: 
      - "PowerShell/*.ps1"
  pull_request:
    branches: [ "main" ]
    paths: 
      - "PowerShell/*.ps1"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path ./PowerShell/ -Recurse -Severity Warning -EnableExit
